# Kubernetes version: 1.26+
#
# Purpose: Defines Grafana configuration for the Task Management System's monitoring stack
#
# Requirements addressed:
# Technical Specification/System Architecture/2.4 Cross-Cutting Concerns
# - Ensures system monitoring and visualization using Grafana for performance and health monitoring
#
# Human Tasks Required:
# 1. Review and update admin credentials for production use
# 2. Verify connectivity to Prometheus and Elasticsearch data sources
# 3. Configure additional security measures if needed
# 4. Set up proper authentication integration for production
# 5. Import and configure required dashboards

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: task-management-system
  labels:
    app: grafana
    component: monitoring
data:
  # Main Grafana configuration file
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000

    [auth]
    disable_login_form = false

    [security]
    admin_user = admin
    admin_password = admin

    [users]
    default_theme = light

    [dashboard]
    home_dashboard_id = 1

    [dataproxy]
    logging = true

  # Data sources configuration
  datasources.yaml: |
    apiVersion: 1
    datasources:
      # Prometheus data source configuration
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090

      # Elasticsearch data source configuration
      - name: Elasticsearch
        type: elasticsearch
        access: proxy
        url: http://elasticsearch:9200
        jsonData:
          esVersion: 7
          timeField: '@timestamp'