# Kubernetes version: 1.26+
# Purpose: Defines the Kubernetes Deployment for the User Service
#
# Requirements addressed:
# 1. User Service Deployment (Technical Specification/System Architecture/2.3.2 Communication Patterns)
#    - Ensures the User Service is deployed with proper configuration, scaling, and resource management
# 2. High Availability (Technical Specification/System Architecture/2.2 Component Details)
#    - Ensures the User Service is highly available with multiple replicas
#
# Human Tasks:
# 1. Verify that the task-management-config ConfigMap exists and contains required configuration
# 2. Ensure task-management-secrets Secret is properly configured with required credentials
# 3. Update the image tag based on your CI/CD pipeline configuration
# 4. Review and adjust resource limits based on performance testing results
# 5. Configure horizontal pod autoscaling if needed for production workloads

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: task-management-system
  labels:
    app: task-management
    component: user-service
  annotations:
    description: "User Service deployment for task management system"
    maintainer: "platform-team"
spec:
  # Ensure high availability with multiple replicas
  replicas: 3
  
  # Pod selection criteria
  selector:
    matchLabels:
      app: task-management
      component: user-service
  
  # Template for pod creation
  template:
    metadata:
      labels:
        app: task-management
        component: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest  # Update with appropriate registry and tag
          imagePullPolicy: Always
          
          # Container port configuration
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          
          # Environment configuration from ConfigMap and Secrets
          envFrom:
            - configMapRef:
                name: task-management-config
            - secretRef:
                name: task-management-secrets
          
          # Resource limits and requests
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          
          # Liveness probe configuration
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          
          # Readiness probe configuration
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          
          # Security context
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          
          # Volume mounts for temporary storage
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      
      # Volumes configuration
      volumes:
        - name: tmp
          emptyDir: {}
      
      # Pod security configuration
      securityContext:
        fsGroup: 1000
      
      # Termination grace period
      terminationGracePeriodSeconds: 30