# Kubernetes version: 1.26+
# Purpose: Horizontal Pod Autoscaler configuration for the Notification Service
#
# Requirements Addressed:
# - Dynamic Scaling (Technical Specification/System Architecture/2.2 Component Details)
#   Ensures the Notification Service can scale dynamically based on CPU and memory usage
#   to handle varying workloads efficiently.
#
# Human Tasks:
# 1. Verify CPU and memory thresholds match production workload patterns
# 2. Configure monitoring to track scaling events and resource utilization
# 3. Set up alerts for sustained high resource utilization
# 4. Review and adjust scaling parameters based on observed patterns

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  namespace: task-management-system
  labels:
    app: notification-service
  annotations:
    description: "Horizontal Pod Autoscaler for the Notification Service"
    last-modified: "2024-01-01"
    scaling-policy: "cpu-memory-based"

spec:
  # Reference to the Deployment to scale
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service

  # Scaling limits
  minReplicas: 2
  maxReplicas: 10

  # Metrics used for scaling decisions
  metrics:
    # CPU utilization target
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

    # Memory utilization target
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

  # Behavior configuration for scaling actions
  behavior:
    scaleUp:
      # Quick scale up to handle traffic spikes
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
      - type: Percent
        value: 100
        periodSeconds: 60
      selectPolicy: Max

    scaleDown:
      # Gradual scale down to prevent service disruption
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      - type: Percent
        value: 20
        periodSeconds: 120
      selectPolicy: Min