# Requirement Addressed: Service Discovery and Load Balancing
# Location: Technical Specification/System Architecture/2.2 Component Details
# Description: Ensures that the Notification Service is discoverable within the Kubernetes cluster 
# and provides load balancing for incoming requests.

apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: default
  labels:
    app: notification-service
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    # Main application port
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    # WebSocket port (same as main port for this service)
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: websocket
  selector:
    app: notification-service
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours